Se incluye la descripción y la espectativa del opuesto de un punto
$ rake
rspec -I. spec/point_spec.rb
....F

Failures:

  1) Point# opuesto de un punto la coordenada x y la coordenada y se multiplican por menos uno
     Failure/Error: p2 = - @p1
     NoMethodError:
       undefined method `-@' for #<Point:0x000000014c6138 @x=1, @y=1>
     # ./spec/point_spec.rb:31:in `block (3 levels) in <top (required)>'

Finished in 0.00793 seconds
5 examples, 1 failure

Failed examples:

rspec ./spec/point_spec.rb:30 # Point# opuesto de un punto la coordenada x y la coordenada y se multiplican por menos uno
rake aborted!
Command failed with status (1): [rspec -I. spec/point_spec.rb...]

Tasks: TOP => default => spec
(See full trace by running task with --trace)