Se incluyen espectativas sobre la comparacion entre puntos basados en la distancia al origen.
$ rake local
(in /home/cleon/clases/lpp13/practicas/prct7/point/CI-Point)
rspec -I. spec/point_spec.rb
......FFFFF

Failures:

  1) Point# comparaciones entre dos puntos basada en su distancia al origen El punto (1,1) es menor que el punto (2,2)
     Failure/Error: test = @p1 < @p2
     NoMethodError:
       undefined method `<' for #<Point:0x8f71900 @x=1, @y=1>
     # ./spec/point_spec.rb:47:in `block (3 levels) in <top (required)>'

  2) Point# comparaciones entre dos puntos basada en su distancia al origen El punto (1,1) es menor o igual que el punto (2,2)
     Failure/Error: test = @p1 <= @p2
     NoMethodError:
       undefined method `<=' for #<Point:0x8f55d7c @x=1, @y=1>
     # ./spec/point_spec.rb:51:in `block (3 levels) in <top (required)>'

  3) Point# comparaciones entre dos puntos basada en su distancia al origen El punto (2,2) es mayor que el punto (1,1)
     Failure/Error: test = @p1 > @p2
     NoMethodError:
       undefined method `>' for #<Point:0x8f53e78 @x=1, @y=1>
     # ./spec/point_spec.rb:55:in `block (3 levels) in <top (required)>'

  4) Point# comparaciones entre dos puntos basada en su distancia al origen El punto (2,2) es mayor o igual que el punto (1,1)
     Failure/Error: test = @p1 >= @p2
     NoMethodError:
       undefined method `>=' for #<Point:0x8f504bc @x=1, @y=1>
     # ./spec/point_spec.rb:59:in `block (3 levels) in <top (required)>'

  5) Point# comparaciones entre dos puntos basada en su distancia al origen El punto (1,1) es igual al punto (1,1)
     Failure/Error: test.should eq(True)
     NameError:
       uninitialized constant True
     # ./spec/point_spec.rb:64:in `block (3 levels) in <top (required)>'

Finished in 0.00386 seconds
11 examples, 5 failures

Failed examples:

rspec ./spec/point_spec.rb:46 # Point# comparaciones entre dos puntos basada en su distancia al origen El punto (1,1) es menor que el punto (2,2)
rspec ./spec/point_spec.rb:50 # Point# comparaciones entre dos puntos basada en su distancia al origen El punto (1,1) es menor o igual que el punto (2,2)
rspec ./spec/point_spec.rb:54 # Point# comparaciones entre dos puntos basada en su distancia al origen El punto (2,2) es mayor que el punto (1,1)
rspec ./spec/point_spec.rb:58 # Point# comparaciones entre dos puntos basada en su distancia al origen El punto (2,2) es mayor o igual que el punto (1,1)
rspec ./spec/point_spec.rb:62 # Point# comparaciones entre dos puntos basada en su distancia al origen El punto (1,1) es igual al punto (1,1)
rake aborted!
Command failed with status (1): [rspec -I. spec/point_spec.rb...]
/home/cleon/clases/lpp13/practicas/prct7/point/CI-Point/Rakefile:9:in `block in <top (required)>'
/home/cleon/.rvm/gems/ruby-2.0.0-p247/bin/ruby_executable_hooks:15:in `eval'
/home/cleon/.rvm/gems/ruby-2.0.0-p247/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => local
(See full trace by running task with --trace)