Se crea una descripción con una espectativa para la suma de dos puntos
$ rake
rspec -I. spec/point_spec.rb
.....F

Failures:

  1) Point# suma de dos puntos  coordenada x = original.x + otro.x, coordenada y = original.y + otro.y
     Failure/Error: p2 = @p1 + @p1
     NoMethodError:
       undefined method `+' for #<Point:0x000000014f5898 @x=1, @y=1>
     # ./spec/point_spec.rb:38:in `block (3 levels) in <top (required)>'

Finished in 0.01588 seconds
6 examples, 1 failure

Failed examples:

rspec ./spec/point_spec.rb:37 # Point# suma de dos puntos  coordenada x = original.x + otro.x, coordenada y = original.y + otro.y
rake aborted!
Command failed with status (1): [rspec -I. spec/point_spec.rb...]

Tasks: TOP => default => spec
(See full trace by running task with --trace)